### ISSUE TITLE
Remove deleted resource from associated Applications

### ISSUE THREAD

**Issue by enjeck** [nextcloud/tables#1027]
### Steps to reproduce

1.Create table/view
2. Create Application with view/table
3. Delete table/view
4. Visit Application

### Expected behavior

The deleted table/view should be removed from the Application

### Actual behavior

Application stuck on loading due to Axios error "Could not fetch table"

### Web server

None

### PHP engine version

None

### Database

None

### Additional info

{
    "message": "Request failed with status code 404",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 404\n    at settle (http://nextcloud.local/apps/tables/js/tables-main.js:245596:12)\n    at XMLHttpRequest.onloadend (http://nextcloud.local/apps/tables/js/tables-main.js:244087:66)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "requesttoken": "4V9idrIBqNsy2XOn3yTi4fHRo46uEs/EmREV+buEc4Y=:ygUQT/t43JoF6DielmeU1baT9tuBIv2Kw1Qmo/XRPMM="
        },
        "method": "get",
        "url": "http://nextcloud.local/ocs/v2.php/apps/tables/api/2/tables/7"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 404
}

**Comment by blizzz** [comment]
It makes to solve this on API / backend level.
