### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/tables#754]
### Steps to reproduce

1. Try to sort a column

### Expected behavior

Sorting works

### Actual behavior

Sorting fails and error is logged in console

### Tables app version

0.6.5

### Browser

Brave Version 1.60.125 Chromium: 119.0.6045.199 (Build officiel) (64 bits)

### Additional info

```
TypeError: Cannot read properties of undefined (reading 'replace')
    at a.value (selection.js:42:14)
    at selection.js:36:24
    at Array.sort (<anonymous>)
    at o.getSearchedAndFilteredAndSortedRows (CustomTable.vue:88:1)
    at e.get (vue.runtime.esm.js:3446:33)
    at e.evaluate (vue.runtime.esm.js:3547:27)
    at o.getSearchedAndFilteredAndSortedRows (vue.runtime.esm.js:5541:25)
    at o.<anonymous> (CustomTable.vue:1:219)
    at e._render (vue.runtime.esm.js:2684:28)
    at o.r (vue.runtime.esm.js:3875:27)
    at e.get (vue.runtime.esm.js:3446:33)
    at e.run (vue.runtime.esm.js:3522:30)
    at kr (vue.runtime.esm.js:4125:17)
    at Array.<anonymous> (vue.runtime.esm.js:3143:20)
    at Nn (vue.runtime.esm.js:3065:16)
```
![image](https://github.com/nextcloud/tables/assets/14975046/52e92390-9ea7-49b3-a692-f6a492d9b249)

**Comment by juliushaertl** [comment]
Can you tell what column type you tried to sort? I assume that not all had an actual value?

**Comment by skjnldsv** [comment]
Sure :)
The `Hub 3` column of the `Supported Apps` table on c.nc.com

**Comment by juliushaertl** [comment]
Seems like https://github.com/nextcloud/tables/pull/693 was missing a backport

**Comment by juliushaertl** [comment]
Backported in #757
