### ISSUE TITLE
Csv export not working 

### ISSUE THREAD

**Issue by adityass35b** [nextcloud/tables#996]
### Steps to reproduce

1.click on export to csv
2.
3.

### Expected behavior

Csv file getting downloaded

### Actual behavior

Csv file not getting downloaded 

### Web server

None

### PHP engine version

None

### Database

None

**Comment by juliushaertl** [comment]
Thanks for reporting. Could you please check the Nextcloud log and browser console for errors?

**Comment by juliushaertl** [comment]
Also please report which version you're using and ideally also if this happens for every table or just some special ones (where the column formats would be interesting)

**Comment by adityass35b** [comment]
Hello the version of tables I am using is 0.6.6 and I got the issue with one table. 
![Screenshot_27](https://github.com/nextcloud/tables/assets/168057173/a7787c85-2eec-4d3c-8d99-df2ee77daee5)
I have uploaded a screenshot of the error message, seems like a variable is null.

**Comment by juliushaertl** [comment]
I thought about this scenario, however I cannot reproduce any issue on 0.7.1 anymore:

- Create a table with some rows
- Add a new text column that has no required content
- Try to export the existing data where a null value could be in place for the new column now

Could you check if the issue still exists on 0.7.1 for you?

**Comment by Manuel-Haas** [comment]
The issue is still present in 0.8.1 (Brave-Browser on Debian 12, Nextcloud AIO Hub 9)

This is, what my json-console told me:

```
Table.vue:1 TypeError: Cannot read properties of null (reading 'replace')
    at s.getValueString (textLine.js:36:28)
    at exportTableMixin.js:29:44
    at Array.forEach (<anonymous>)
    at exportTableMixin.js:25:13
    at Array.forEach (<anonymous>)
    at o.downloadCsv (exportTableMixin.js:23:9)
    at o.downloadCSV (MainWrapper.vue:95:1)
    at pn (vue.runtime.esm.js:3033:30)
    at o.n (vue.runtime.esm.js:1832:20)
    at pn (vue.runtime.esm.js:3033:30)
mn @ vue.runtime.esm.js:3065
hn @ vue.runtime.esm.js:3057
dn @ vue.runtime.esm.js:3024
pn @ vue.runtime.esm.js:3040
n @ vue.runtime.esm.js:1832
pn @ vue.runtime.esm.js:3033
(anonymous) @ vue.runtime.esm.js:3732
download-csv @ Table.vue:1
pn @ vue.runtime.esm.js:3033
n @ vue.runtime.esm.js:1832
pn @ vue.runtime.esm.js:3033
(anonymous) @ vue.runtime.esm.js:3732
click @ DataTable.vue:1
pn @ vue.runtime.esm.js:3033
n @ vue.runtime.esm.js:1832
pn @ vue.runtime.esm.js:3033
(anonymous) @ vue.runtime.esm.js:3732
onClick @ actionText-fFcUPi2g.mjs:77
handleClick @ NcActionButton.mjs:131
pn @ vue.runtime.esm.js:3033
n @ vue.runtime.esm.js:1832
o.85471.r._wrapper @ vue.runtime.esm.js:7500
Show 20 more frames
Show less
VM534:1 Uncaught SyntaxError: Unexpected token 'I', "Invalid credentials" is not valid JSON
    at JSON.parse (<anonymous>)
    at Zi.window._notify_push_ws.onmessage (NotificationsApp-CX_2Ib0T.chunk.mjs:34:23320)
Zi.window._notify_push_ws.onmessage @ NotificationsApp-CX_2Ib0T.chunk.mjs:34
VM536:1 Uncaught SyntaxError: Unexpected token 'I', "Invalid credentials" is not valid JSON
    at JSON.parse (<anonymous>)
    at Zi.window._notify_push_ws.onmessage (NotificationsApp-CX_2Ib0T.chunk.mjs:34:23320)
Zi.window._notify_push_ws.onmessage @ NotificationsApp-CX_2Ib0T.chunk.mjs:34
VM538:1 Uncaught SyntaxError: Unexpected token 'I', "Invalid credentials" is not valid JSON
    at JSON.parse (<anonymous>)
    at Zi.window._notify_push_ws.onmessage (NotificationsApp-CX_2Ib0T.chunk.mjs:34:23320)
Zi.window._notify_push_ws.onmessage @ NotificationsApp-CX_2Ib0T.chunk.mjs:34
```

**Comment by tcitworld** [comment]
I have occurred the issue as well, here are the reproduction steps :

- create a table
- create a view
- create an app using the view
- when on this app, click on "Export to CSV"

Exporting to CSV works correctly in all other cases (exporting directly from a table, a view or an app using a table).

Affected versions : 0.8.4 and 0.8.1

**Comment by enjeck** [comment]
should be now fixed
